image: docker:latest
services:
  - docker:dind

#cache:
#  paths:
#    - .m2/

variables:
  SPRING_PROFILE_ACTIVE: prod
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  ARTIFACT_ID_SCRIPT: '$ARTIFACT_ID=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.artifactId | grep -ov "INFO" | grep -ov "Down" | grep -ov "Prog")'
  POM_VERSION_SCRIPT: '$POM_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -ov "INFO" | grep -ov "Down" | grep -ov "Prog")'
  ARTIFACT_NAME: "${ARTIFACT_ID}-${POM_VERSION}-jar-with-dependencies.jar"
  IMAGE_NAME: "mustafasisman/${ARTIFACT_ID}:${POM_VERSION}"

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - eval ARTIFACT_ID_SCRIPT
    - echo $ARTIFACT_ID
#    - mvn -U clean install
#    - eval ARTIFACT_ID
#    - eval $POM_VERSION
#    - eval $ARTIFACT_NAME
#    - eval $IMAGE_NAME
  artifacts:
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/lib/

docker-build:
  stage: package
  script:
    - docker build -t ${IMAGE_NAME} --build-arg ARTIFACT_NAME=${ARTIFACT_NAME} --no-cache .
