image: docker:18-git

services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  SPRING_PROFILE_ACTIVE: prod

stages:
  - build
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY

maven-docker-build:
  image: twalter/maven-docker:latest
  stage: build
  only:
    - tags
  script:
    - mvn clean package
    - IMAGE_NAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - ARTIFACT_NAME=$CI_PROJECT_NAMESPACE-$CI_COMMIT_TAG.jar
    - docker build -t $IMAGE_NAME --build-arg ARTIFACT_NAME=$ARTIFACT_NAME --no-cache .
    - docker push $IMAGE_NAME

deploy_to_server:
  image: twalter/maven-docker:latest
  stage: deploy
  only:
    - tags
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 142.93.239.61 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh arif@142.93.239.61 "hostname -I && (docker rm -vf p2g-web || true) && docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG && docker run -d --name p2g-web -p 8080:8080 $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG && exit"
  after_script:
    - echo