image: docker:18-git

services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  SPRING_PROFILE_ACTIVE: prod
  ARTIFACT_ID_SCRIPT: "mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.artifactId | grep -Eiv 'INFO|Down|Prog'"
  POM_VERSION_SCRIPT: "mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Eiv 'INFO|Down|Prog'"

stages:
  - build
  - push

maven-docker-build:
  image: twalter/maven-docker:latest
  stage: build
  script:
    - mvn clean package
#    - eval ARTIFACT_ID=\$\($ARTIFACT_ID_SCRIPT\)
    - eval POM_VERSION=\$\($POM_VERSION_SCRIPT\)
    - ARTIFACT_NAME=$CI_PROJECT_NAME-$POM_VERSION-jar-with-dependencies.jar
    - IMAGE_NAME=$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$POM_VERSION
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_NAME --build-arg ARTIFACT_NAME=$ARTIFACT_NAME --build-arg SPRING_PROFILE_ACTIVE=$SPRING_PROFILE_ACTIVE --no-cache .
    - docker push $IMAGE_NAME
  artifacts:
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/lib/

#push_when_tag:
#  stage: push
#  only:
#    - tags
#  script:
#    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
#    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME