image: docker:18-git

services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  SPRING_PROFILE_ACTIVE: prod
  ARTIFACT_ID_SCRIPT: "mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.artifactId | grep -Eiv 'INFO|Down|Prog'"
  POM_VERSION_SCRIPT: "mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Eiv 'INFO|Down|Prog'"

stages:
  - build
  - package

#maven-build:
#  image: maven:3-jdk-8
#  stage: build
#  script:
  #    - mvn -U clean install
  #    - eval ARTIFACT_ID=\$\($ARTIFACT_ID_SCRIPT\)
  #    - eval POM_VERSION=\$\($POM_VERSION_SCRIPT\)
  #    - ARTIFACT_NAME=$ARTIFACT_ID-$POM_VERSION-jar-with-dependencies.jar
  #    - IMAGE_NAME=mustafasisman/$ARTIFACT_ID:$POM_VERSION
#  artifacts:
#    paths:
#      - $CI_PROJECT_DIR/target/
#      - $CI_PROJECT_DIR/lib/

docker-build:
  image: twalter/maven-docker:latest
  stage: package
  script:
    - eval ARTIFACT_ID=\$\($ARTIFACT_ID_SCRIPT\)
    - eval POM_VERSION=\$\($POM_VERSION_SCRIPT\)
    - IMAGE_NAME=mustafasisman/$ARTIFACT_ID:$POM_VERSION
    - ARTIFACT_NAME=$ARTIFACT_ID-$POM_VERSION-jar-with-dependencies.jar
    - docker build -t $IMAGE_NAME --build-arg ARTIFACT_NAME=$ARTIFACT_NAME --no-cache .
