image: docker:latest
services:
  - docker:dind

cache:
  paths:
    - .m2/

variables:
  SPRING_PROFILE_ACTIVE: prod
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo $CI_PROJECT_DIR
    - mvn clean install
  artifacts:
    paths:
      -  $CI_PROJECT_DIR/target/*.jar

docker-build:
  stage: package
  script:
    - grep -v
    - ARTIFACT_ID=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.artifactId | grep -ov "INFO" | grep -ov "Down" | grep -ov "Prog")
    - POM_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -ov "INFO" | grep -ov "Down" | grep -ov "Prog")
    - ARTIFACT_NAME="${ARTIFACT_ID}-${POM_VERSION}.jar"
    - IMAGE_NAME="mustafasisman/${ARTIFACT_ID}:${POM_VERSION}"
    - CONTAINER_NAME=${ARTIFACT_ID}
    - docker build -t ${IMAGE_NAME} --build-arg ARTIFACT_NAME=${ARTIFACT_NAME} --no-cache .
