image: maven:latest

stages:
  - build

build:
  stage: build
  script:
    - ./docker-init.sh
#    - mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.artifactId
    - grep --version