# Configures the port that Eureka Server will be running
server:
  port: 8097

# Configure active spring profile
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: ${JPA_HIBERNATE_MODE}
    database: postgresql
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc.lob.non_contextual_creation: true

security:
  oauth2:
    resource:
      user-info-uri: https://api.spotify.com/v1/me