# Configures the port that Eureka Server will be running
server:
  port: 8097

# Configure active spring profile
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://142.93.239.61:5432/p2g_db
    username: postgres
    password: -$aSpOW$gUd$epO2O5p6
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc.lob.non_contextual_creation: true

security:
  oauth2:
    resource:
      user-info-uri: https://api.spotify.com/v1/me

DATA_INIT_FLAG: false