#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:file:~/test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate.ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: true
#        jdbc.lob.non_contextual_creation: true