# configures the port that Eureka Server will be running
server:
  port: 8080

# Data source configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/p2g_db
    username: postgres
    password: 16181618
    initialization-mode: never

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc.lob.non_contextual_creation: true


# Spotify configuration
spotify:
  clientId: zyuxhfo1c51b5hxjk09x2uhv5n0svgd6g
  clientSecret: zudknyqbh3wunbhcvg9uyvo7uwzeu6nne
  recirectUrl: https://example.com/spotify-redirect